483:52:39.175192 MainPower Log continuation - Log started 2024-02-20T09:23:59.269604600Z
483:52:41.343074 dns-monitor HostDnsMonitor: updating information
483:52:41.343167 dns-monitor HostDnsMonitor: old information
483:52:41.343185 dns-monitor   server 1: 192.168.100.183
483:52:41.343199 dns-monitor   no domain set
483:52:41.343212 dns-monitor   no search string entries
483:52:41.343224 dns-monitor HostDnsMonitor: new information
483:52:41.343236 dns-monitor   no server entries
483:52:41.343247 dns-monitor   no domain set
483:52:41.343259 dns-monitor   no search string entries
483:52:44.051272 dns-monitor HostDnsMonitor: updating information
483:52:44.051316 dns-monitor HostDnsMonitor: old information
483:52:44.051329 dns-monitor   no server entries
483:52:44.055663 dns-monitor   no domain set
483:52:44.055678 dns-monitor   no search string entries
483:52:44.055685 dns-monitor HostDnsMonitor: new information
483:52:44.055690 dns-monitor   server 1: 192.168.1.1
483:52:44.055695 dns-monitor   domain: zyxel.com
483:52:44.055699 dns-monitor   no search string entries
483:53:02.559867 USBPROXY usbLibGetDevices: Starting USB device enumeration
483:53:02.572399 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&22224d6e&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 3
483:53:02.572516 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&22224d6e&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 10
483:53:02.572676 USBPROXY usbLibGetDevices: Found 2 USB devices, 0 captured
483:53:07.707443 USBPROXY usbLibGetDevices: Starting USB device enumeration
483:53:07.720081 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&22224d6e&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 3
483:53:07.720184 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&22224d6e&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 10
483:53:07.720323 USBPROXY usbLibGetDevices: Found 2 USB devices, 0 captured
483:54:27.183475 USBPROXY usbLibGetDevices: Starting USB device enumeration
483:54:27.196240 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&22224d6e&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 3
483:54:27.196422 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&22224d6e&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 10
483:54:27.196801 USBPROXY usbLibGetDevices: Found 2 USB devices, 0 captured
483:57:57.309444 USBPROXY usbLibGetDevices: Starting USB device enumeration
483:57:57.322278 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&22224d6e&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 3
483:57:57.322383 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&22224d6e&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 10
483:57:57.322568 USBPROXY usbLibGetDevices: Found 2 USB devices, 0 captured
483:58:11.264473 USBPROXY usbLibGetDevices: Starting USB device enumeration
483:58:11.278551 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&22224d6e&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 3
483:58:11.278733 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&22224d6e&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 10
483:58:11.278884 USBPROXY usbLibGetDevices: Found 2 USB devices, 0 captured
484:00:33.800445          Saving settings file "C:\Users\Admin\VirtualBox VMs\Linux\Linux.vbox" with version "1.19-windows"
484:00:33.804302          Finished saving settings file "C:\Users\Admin\VirtualBox VMs\Linux\Linux.vbox"
484:00:40.326737 main     VirtualBox: object deletion starts
484:00:40.329950 main     ERROR [COM]: aRC=VBOX_E_OBJECT_IN_USE (0x80bb000c) aIID={ad47ad09-787b-44ab-b343-a082a3f2dfb1} aComponent={MediumWrap} aText={Medium 'C:\Users\Admin\VirtualBox VMs\Linux\Linux.vdi' cannot be closed because it is still attached to 1 virtual machines}, preserve=false aResultDetail=0
484:00:40.341595 main     HostDnsMonitor: shutting down ...
484:00:40.341877 main     HostDnsMonitor: shut down
484:00:40.346873 Watcher  ERROR [COM]: aRC=E_ACCESSDENIED (0x80070005) aIID={7682d5eb-f00e-44f1-8ca2-99d08b1cd607} aComponent={VirtualBoxWrap} aText={The object is not ready}, preserve=false aResultDetail=0
484:00:40.347288 main     VirtualBox: object deleted
